<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LibProsperoPkg.Gui</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Photino.NET" Version="4.0.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../decompiled/LibProsperoPkg.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
